# Generated by Django 4.1 on 2022-08-10 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('synopsis', models.TextField(blank=True, max_length=500, null=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('directors', models.CharField(blank=True, max_length=400, null=True)),
                ('genres', models.CharField(blank=True, max_length=400, null=True)),
                ('tags', models.CharField(blank=True, max_length=400, null=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('runtime', models.FloatField(blank=True, null=True)),
                ('n_watches', models.IntegerField(blank=True, null=True)),
                ('have_watched', models.BooleanField(default=False)),
                ('on_watchlist', models.BooleanField(default=False)),
                ('first_watch', models.DateField(blank=True, null=True)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
