# Generated by Django 4.1 on 2022-08-12 05:14

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_based_on_movie_distributor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
