# Generated by Django 4.1 on 2022-08-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(),
        ),
    ]
