# Generated by Django 4.1 on 2022-08-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
