# Generated by Django 4.1 on 2022-08-12 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_movie_is_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='trailer_url',
        ),
    ]
